"""
Abductive Theory Former Module for GPDISC

Generates novel scientific hypotheses through abductive reasoning (inference to
best explanation). This is the foundational module that enables GPDISC to
transition from knowledge retrieval to knowledge creation.

Key capabilities:
- Hypothesis generation: Create novel, testable scientific hypotheses
- Knowledge gap identification: Find gaps in current biological knowledge
- Theory synthesis: Combine disparate findings into coherent theories
- Mechanism explanation: Propose mechanistic explanations for phenomena

Date: 2026-04-22
Version: 1.0.0
"""

from typing import Dict, List, Any, Optional, Tuple, Set
from dataclasses import dataclass, field
from enum import Enum
import logging
import numpy as np
from collections import defaultdict

logger = logging.getLogger(__name__)

# Try to import existing abductive inference capabilities
try:
    from gpdisc_core.capabilities.abductive_inference import (
        AbductiveInferenceEngine,
        Hypothesis as AbductiveHypothesis,
        Observation,
        Evidence,
        ExplanationQuality
    )
    ABDUCTIVE_INFERENCE_AVAILABLE = True
except ImportError:
    ABDUCTIVE_INFERENCE_AVAILABLE = False
    logger.warning("Abductive inference engine not available, using fallback")


class HypothesisType(Enum):
    """Types of scientific hypotheses"""
    CAUSAL = "causal"  # X causes Y
    MECHANISTIC = "mechanistic"  # X works through mechanism Y
    COMPARATIVE = "comparative"  # X differs from Y in aspect Z
    TEMPORAL = "temporal"  # X precedes/influences Y over time
    INTERVENTION = "intervention"  # Manipulating X affects Y
    INTEGRATIVE = "integrative"  # Integrates multiple phenomena


class ConfidenceLevel(Enum):
    """Confidence levels for hypotheses"""
    VERY_LOW = 1
    LOW = 2
    MODERATE = 3
    HIGH = 4
    VERY_HIGH = 5


@dataclass
class Hypothesis:
    """
    A scientific hypothesis generated by abductive reasoning

    Attributes:
        statement: The hypothesis statement
        hypothesis_type: Type of hypothesis
        confidence: Confidence level (1-5)
        evidence: Supporting evidence
        predictions: Testable predictions
        falsifiable: Whether hypothesis is falsifiable
        novelty: Novelty score (0-1)
        plausibility: Plausibility score (0-1)
        source_domains: Which domains contributed to this hypothesis
        mechanisms: Proposed mechanisms (if mechanistic hypothesis)
        knowledge_gaps: Related knowledge gaps
    """
    statement: str
    hypothesis_type: HypothesisType
    confidence: ConfidenceLevel
    evidence: List[str] = field(default_factory=list)
    predictions: List[str] = field(default_factory=list)
    falsifiable: bool = True
    novelty: float = 0.5
    plausibility: float = 0.5
    source_domains: List[str] = field(default_factory=list)
    mechanisms: List[str] = field(default_factory=list)
    knowledge_gaps: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'statement': self.statement,
            'type': self.hypothesis_type.value,
            'confidence': self.confidence.value,
            'evidence': self.evidence,
            'predictions': self.predictions,
            'falsifiable': self.falsifiable,
            'novelty': self.novelty,
            'plausibility': self.plausibility,
            'source_domains': self.source_domains,
            'mechanisms': self.mechanisms,
            'knowledge_gaps': self.knowledge_gaps
        }


@dataclass
class KnowledgeGap:
    """
    A gap in current biological knowledge

    Attributes:
        description: Description of the knowledge gap
        domain: Which domain(s) this gap relates to
        importance: How important filling this gap is (1-5)
        fillable: Whether this gap is currently fillable with existing techniques
        related_hypotheses: Hypotheses that could fill this gap
    """
    description: str
    domain: str
    importance: int = 3
    fillable: bool = True
    related_hypotheses: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'description': self.description,
            'domain': self.domain,
            'importance': self.importance,
            'fillable': self.fillable,
            'related_hypotheses': self.related_hypotheses
        }


@dataclass
class Theory:
    """
    A synthesized scientific theory combining multiple hypotheses

    Attributes:
        name: Name of the theory
        description: Description of the theory
        hypotheses: Constituent hypotheses
        coherence: How coherent the theory is (0-1)
        explanatory_power: How much the theory explains (0-1)
        predictions: Testable predictions
        scope: Scope of the theory
    """
    name: str
    description: str
    hypotheses: List[Hypothesis] = field(default_factory=list)
    coherence: float = 0.5
    explanatory_power: float = 0.5
    predictions: List[str] = field(default_factory=list)
    scope: str = "specific"

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'name': self.name,
            'description': self.description,
            'hypotheses': [h.to_dict() for h in self.hypotheses],
            'coherence': self.coherence,
            'explanatory_power': self.explanatory_power,
            'predictions': self.predictions,
            'scope': self.scope
        }


@dataclass
class Mechanism:
    """
    A proposed mechanistic explanation

    Attributes:
        phenomenon: The phenomenon being explained
        steps: Mechanistic steps
        entities: Key entities involved
        interactions: Key interactions
        dynamics: Temporal dynamics
        confidence: Confidence in the mechanism
    """
    phenomenon: str
    steps: List[str] = field(default_factory=list)
    entities: List[str] = field(default_factory=list)
    interactions: List[str] = field(default_factory=list)
    dynamics: str = ""
    confidence: float = 0.5

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            'phenomenon': self.phenomenon,
            'steps': self.steps,
            'entities': self.entities,
            'interactions': self.interactions,
            'dynamics': self.dynamics,
            'confidence': self.confidence
        }


class HypothesisGenerator:
    """
    Generates novel scientific hypotheses through abductive reasoning

    Uses abduction (inference to best explanation) to generate hypotheses
    that explain observed phenomena in terms of unobserved causes.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize Hypothesis Generator

        Args:
            config: Configuration dictionary
        """
        self.config = config or {}

        # Initialize abductive inference engine if available
        self.abductive_engine = None
        if ABDUCTIVE_INFERENCE_AVAILABLE:
            try:
                self.abductive_engine = AbductiveInferenceEngine()
                logger.info("Abductive inference engine initialized")
            except Exception as e:
                logger.warning(f"Could not initialize abductive engine: {e}")

        # Hypothesis templates for different types
        self.templates = {
            HypothesisType.CAUSAL: [
                "{X} causes {Y} through {mechanism}",
                "{X} is necessary for {Y}",
                "Increased {X} leads to {Y}",
                "Absence of {X} results in {Y}"
            ],
            HypothesisType.MECHANISTIC: [
                "{X} acts through {pathway} to affect {Y}",
                "{X} modulates {Y} by {mechanism}",
                "The effect of {X} on {Y} is mediated by {mediator}",
                "{X} influences {Y} via {mechanism} at {scale}"
            ],
            HypothesisType.COMPARATIVE: [
                "{X} differs from {Y} in {aspect}",
                "Unlike {Y}, {X} exhibits {property}",
                "{X} and {Y} share {mechanism} but differ in {aspect}",
                "The relationship between {X} and {Y} depends on {condition}"
            ],
            HypothesisType.TEMPORAL: [
                "{X} precedes and influences {Y}",
                "Changes in {X} predict later changes in {Y}",
                "{X} at {time1} affects {Y} at {time2}",
                "Temporal dynamics of {X} drive {Y}"
            ],
            HypothesisType.INTERVENTION: [
                "Manipulating {X} will affect {Y}",
                "Inhibition of {X} will {outcome} {Y}",
                "Enhancing {X} will {outcome} {Y}",
                "Targeting {X} at {level} will modulate {Y}"
            ],
            HypothesisType.INTEGRATIVE: [
                "{X} and {Y} interact to produce {Z}",
                "The combination of {X} and {Y} explains {Z}",
                "{X}, {Y}, and {Z} form a regulatory network controlling {outcome}",
                "Cross-talk between {pathway1} and {pathway2} regulates {outcome}"
            ]
        }

        # Biological entities and processes for hypothesis generation
        self.biological_entities = [
            # Proteins
            "protein folding", "protein aggregation", "chaperones", "proteasome",
            "post-translational modification", "protein degradation",
            # Nucleic acids
            "DNA replication", "transcription", "translation", "RNA splicing",
            "epigenetic modification", "chromatin remodeling",
            # Cellular processes
            "cell cycle", "apoptosis", "autophagy", "metabolism",
            "signal transduction", "vesicle trafficking",
            # Molecular interactions
            "protein-protein interactions", "protein-DNA interactions",
            "enzyme catalysis", "allosteric regulation",
            # Systems
            "gene regulatory networks", "metabolic pathways", "signaling pathways"
        ]

    def generate(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None,
        num_hypotheses: int = 5
    ) -> List[Hypothesis]:
        """
        Generate hypotheses for a given query

        Args:
            query: Scientific query or phenomenon
            context: Additional context (data, constraints, etc.)
            num_hypotheses: Number of hypotheses to generate

        Returns:
            List of generated hypotheses
        """
        context = context or {}
        hypotheses = []

        try:
            # Extract key terms from query
            key_terms = self._extract_key_terms(query)

            # Generate hypotheses of different types
            for h_type in HypothesisType:
                if len(hypotheses) >= num_hypotheses:
                    break

                # Generate hypothesis using templates
                hypothesis = self._generate_hypothesis_of_type(
                    query, h_type, key_terms, context
                )
                if hypothesis:
                    hypotheses.append(hypothesis)

            # If using abductive inference engine, generate additional hypotheses
            if self.abductive_engine and len(hypotheses) < num_hypotheses:
                abductive_hypotheses = self._generate_abductive_hypotheses(
                    query, context, num_hypotheses - len(hypotheses)
                )
                hypotheses.extend(abductive_hypotheses)

            # Score and rank hypotheses
            hypotheses = self._score_and_rank_hypotheses(hypotheses, query, context)

            # Add predictions to hypotheses
            for h in hypotheses:
                h.predictions = self._generate_predictions(h, query, context)

            logger.info(f"Generated {len(hypotheses)} hypotheses for query")

        except Exception as e:
            logger.error(f"Error generating hypotheses: {e}")

        return hypotheses[:num_hypotheses]

    def _extract_key_terms(self, query: str) -> List[str]:
        """Extract key biological terms from query"""
        # Simple keyword extraction (can be enhanced with NLP)
        key_terms = []
        query_lower = query.lower()

        for entity in self.biological_entities:
            if entity in query_lower:
                key_terms.append(entity)

        return key_terms

    def _generate_hypothesis_of_type(
        self,
        query: str,
        h_type: HypothesisType,
        key_terms: List[str],
        context: Dict[str, Any]
    ) -> Optional[Hypothesis]:
        """Generate a hypothesis of a specific type"""

        templates = self.templates.get(h_type, [])
        if not templates:
            return None

        # Select a template (can be made more sophisticated)
        template = np.random.choice(templates)

        # Fill template with appropriate entities
        # This is a simplified version - can be enhanced with domain knowledge
        statement = template.format(
            X=key_terms[0] if len(key_terms) > 0 else "upstream regulator",
            Y=key_terms[1] if len(key_terms) > 1 else "downstream target",
            mechanism="molecular interaction",
            pathway="signaling cascade",
            mediator="intermediate factor",
            scale="cellular level",
            aspect="activity level",
            property="response kinetics",
            condition="specific contexts",
            time1="early time points",
            time2="later time points",
            outcome="modulate",
            level="expression level",
            pathway1="primary pathway",
            outcome2="combined effect",
            Z=key_terms[2] if len(key_terms) > 2 else "emergent property"
        )

        # Calculate scores
        novelty = self._calculate_novelty(statement, context)
        plausibility = self._calculate_plausibility(statement, context)

        hypothesis = Hypothesis(
            statement=statement,
            hypothesis_type=h_type,
            confidence=ConfidenceLevel.MODERATE,
            novelty=novelty,
            plausibility=plausibility,
            source_domains=self._identify_source_domains(query, key_terms)
        )

        return hypothesis

    def _generate_abductive_hypotheses(
        self,
        query: str,
        context: Dict[str, Any],
        num_hypotheses: int
    ) -> List[Hypothesis]:
        """Generate hypotheses using abductive inference engine"""
        hypotheses = []

        if not self.abductive_engine:
            return hypotheses

        try:
            # Create observations from query
            observations = self._query_to_observations(query, context)

            # Use abductive engine to generate hypotheses
            for obs in observations[:num_hypotheses]:
                abductive_result = self.abductive_engine.generate_hypotheses(obs)

                # Convert to BCDL Hypothesis format
                for abd_hyp in abductive_result.get('hypotheses', [])[:3]:
                    hypothesis = Hypothesis(
                        statement=abd_hyp.get('statement', ''),
                        hypothesis_type=HypothesisType.CAUSAL,
                        confidence=ConfidenceLevel(abd_hyp.get('quality', 3)),
                        evidence=abd_hyp.get('evidence', []),
                        novelty=abd_hyp.get('novelty', 0.5),
                        plausibility=abd_hyp.get('plausibility', 0.5)
                    )
                    hypotheses.append(hypothesis)

        except Exception as e:
            logger.error(f"Error in abductive hypothesis generation: {e}")

        return hypotheses

    def _query_to_observations(
        self,
        query: str,
        context: Dict[str, Any]
    ) -> List[Observation]:
        """Convert query to observation format for abductive engine"""
        # Simplified conversion - can be enhanced
        observations = []

        # Extract phenomena from query
        if "cause" in query.lower():
            obs_type = "causal_relationship"
        elif "mechanism" in query.lower():
            obs_type = "mechanism"
        elif "differ" in query.lower():
            obs_type = "comparison"
        else:
            obs_type = "general"

        obs = Observation(
            content=query,
            obs_type=obs_type,
            context=context
        )
        observations.append(obs)

        return observations

    def _score_and_rank_hypotheses(
        self,
        hypotheses: List[Hypothesis],
        query: str,
        context: Dict[str, Any]
    ) -> List[Hypothesis]:
        """Score and rank hypotheses by quality"""

        for h in hypotheses:
            # Calculate composite score
            score = (
                0.3 * h.novelty +
                0.3 * h.plausibility +
                0.2 * (1.0 if h.falsifiable else 0.0) +
                0.2 * len(h.source_domains) / 10.0  # Diversity of sources
            )

            # Update confidence based on score
            if score > 0.7:
                h.confidence = ConfidenceLevel.HIGH
            elif score > 0.5:
                h.confidence = ConfidenceLevel.MODERATE
            else:
                h.confidence = ConfidenceLevel.LOW

        # Sort by composite score
        hypotheses.sort(key=lambda h: (
            0.3 * h.novelty +
            0.3 * h.plausibility +
            0.2 * (1.0 if h.falsifiable else 0.0) +
            0.2 * len(h.source_domains) / 10.0
        ), reverse=True)

        return hypotheses

    def _calculate_novelty(self, statement: str, context: Dict[str, Any]) -> float:
        """Calculate novelty score for a hypothesis"""
        # Simplified novelty calculation
        # Can be enhanced by checking against literature database

        # High novelty if combines uncommon terms
        novelty = 0.5

        # Increase novelty for mechanistic explanations
        if "mechanism" in statement.lower():
            novelty += 0.2

        # Increase novelty for multi-scale explanations
        scale_terms = ["molecular", "cellular", "tissue", "organism"]
        scale_count = sum(1 for term in scale_terms if term in statement.lower())
        novelty += 0.1 * scale_count

        return min(novelty, 1.0)

    def _calculate_plausibility(self, statement: str, context: Dict[str, Any]) -> float:
        """Calculate plausibility score for a hypothesis"""
        # Simplified plausibility calculation
        # Can be enhanced with domain knowledge and constraints

        plausibility = 0.5

        # Increase plausibility for well-established mechanisms
        if any(term in statement.lower() for term in ["pathway", "regulation", "modulates"]):
            plausibility += 0.2

        # Decrease plausibility for overly speculative claims
        if any(term in statement.lower() for term in ["must", "certainly", "definitely"]):
            plausibility -= 0.2

        return max(0.0, min(plausibility, 1.0))

    def _identify_source_domains(self, query: str, key_terms: List[str]) -> List[str]:
        """Identify which domains are relevant to this hypothesis"""
        domains = []

        # Domain keywords
        domain_keywords = {
            'molecular_biology': ['protein', 'dna', 'rna', 'transcription', 'translation'],
            'biochemistry': ['enzyme', 'metabolism', 'catalysis', 'pathway'],
            'genetics': ['gene', 'mutation', 'inheritance', 'genotype'],
            'cell_biology': ['cell', 'organelle', 'membrane', 'division'],
            'biophysics': ['force', 'energy', 'structure', 'dynamics'],
            'bioinformatics': ['sequence', 'alignment', 'database'],
            'computational_biology': ['model', 'simulation', 'network'],
            'genomics': ['genome', 'sequencing', 'annotation'],
            'proteomics': ['proteome', 'mass spectrometry'],
            'systems_biology': ['network', 'integration', 'emergent']
        }

        for domain, keywords in domain_keywords.items():
            if any(kw in query.lower() for kw in keywords):
                domains.append(domain)

        return domains if domains else ['molecular_biology']  # Default

    def _generate_predictions(
        self,
        hypothesis: Hypothesis,
        query: str,
        context: Dict[str, Any]
    ) -> List[str]:
        """Generate testable predictions from a hypothesis"""
        predictions = []

        # Generate predictions based on hypothesis type
        if hypothesis.hypothesis_type == HypothesisType.CAUSAL:
            predictions.append(f"If {hypothesis.statement.split(' causes ')[0]} is manipulated, the predicted outcome should change")
            predictions.append("The effect should be dose-dependent")

        elif hypothesis.hypothesis_type == HypothesisType.MECHANISTIC:
            predictions.append("Interruption of the proposed pathway should abolish the effect")
            predictions.append("Downstream components should be affected")

        elif hypothesis.hypothesis_type == HypothesisType.INTERVENTION:
            predictions.append("The intervention should produce measurable changes")
            predictions.append("Effects should be reversible upon intervention withdrawal")

        # Add general predictions
        predictions.append("The effect should be reproducible across experimental replicates")
        predictions.append("Control experiments should show no significant effect")

        return predictions


class KnowledgeGapIdentifier:
    """
    Identifies gaps in current biological knowledge

    Finds areas where current knowledge is incomplete, inconsistent,
    or missing, which are opportunities for new discoveries.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize Knowledge Gap Identifier

        Args:
            config: Configuration dictionary
        """
        self.config = config or {}

        # Common patterns indicating knowledge gaps
        self.gap_patterns = [
            "unknown mechanism",
            "poorly understood",
            "not well characterized",
            "remains unclear",
            "further investigation needed",
            "controversial",
            "inconsistent findings"
        ]

    def identify(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None,
        num_gaps: int = 5
    ) -> List[KnowledgeGap]:
        """
        Identify knowledge gaps related to a query

        Args:
            query: Scientific query or phenomenon
            context: Additional context
            num_gaps: Number of gaps to identify

        Returns:
            List of identified knowledge gaps
        """
        context = context or {}
        gaps = []

        try:
            # Analyze query to identify potential gaps
            key_terms = self._extract_key_concepts(query)

            # Generate gaps based on query type
            if "how" in query.lower() or "mechanism" in query.lower():
                gaps.append(KnowledgeGap(
                    description=f"Molecular mechanism of {query}",
                    domain="molecular_biology",
                    importance=5,
                    fillable=True
                ))

            if "cause" in query.lower():
                gaps.append(KnowledgeGap(
                    description=f"Causal factors for {query}",
                    domain="genetics",
                    importance=5,
                    fillable=True
                ))

            # Identify cross-domain gaps
            gaps.extend(self._identify_cross_domain_gaps(query, key_terms))

            # Identify scale gaps
            gaps.extend(self._identify_scale_gaps(query, key_terms))

            # Score and rank gaps by importance
            gaps.sort(key=lambda g: g.importance, reverse=True)

            logger.info(f"Identified {len(gaps)} knowledge gaps")

        except Exception as e:
            logger.error(f"Error identifying knowledge gaps: {e}")

        return gaps[:num_gaps]

    def _extract_key_concepts(self, query: str) -> List[str]:
        """Extract key concepts from query"""
        # Simplified concept extraction
        words = query.lower().split()
        # Filter out common words
        key_concepts = [w for w in words if len(w) > 4 and w.isalpha()]
        return list(set(key_concepts))

    def _identify_cross_domain_gaps(
        self,
        query: str,
        key_terms: List[str]
    ) -> List[KnowledgeGap]:
        """Identify gaps that span multiple domains"""
        gaps = []

        # Look for integration gaps
        if len(key_terms) > 1:
            gaps.append(KnowledgeGap(
                description=f"Integration of {key_terms[0]} and {key_terms[1]} mechanisms",
                domain="systems_biology",
                importance=4,
                fillable=True
            ))

        return gaps

    def _identify_scale_gaps(
        self,
        query: str,
        key_terms: List[str]
    ) -> List[KnowledgeGap]:
        """Identify gaps across biological scales"""
        gaps = []

        # Check for multi-scale understanding
        scales = ['molecular', 'cellular', 'tissue', 'organism']
        found_scales = [s for s in scales if s in query.lower()]

        if len(found_scales) > 1:
            gaps.append(KnowledgeGap(
                description=f"Cross-scale mechanisms connecting {' and '.join(found_scales)}",
                domain="systems_biology",
                importance=4,
                fillable=True
            ))

        return gaps


class TheorySynthesizer:
    """
    Synthesizes disparate findings into coherent theories

    Combines multiple hypotheses and evidence into unified theories
    that explain a wide range of phenomena.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize Theory Synthesizer

        Args:
            config: Configuration dictionary
        """
        self.config = config or {}

    def synthesize(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None,
        hypotheses: Optional[List[Hypothesis]] = None
    ) -> Theory:
        """
        Synthesize a theory from hypotheses

        Args:
            query: Scientific query or phenomenon
            context: Additional context
            hypotheses: List of hypotheses to synthesize

        Returns:
            Synthesized theory
        """
        context = context or {}
        hypotheses = hypotheses or []

        try:
            # Generate theory name
            name = self._generate_theory_name(query)

            # Generate theory description
            description = self._generate_theory_description(
                query, hypotheses, context
            )

            # Calculate coherence
            coherence = self._calculate_coherence(hypotheses)

            # Calculate explanatory power
            explanatory_power = self._calculate_explanatory_power(
                hypotheses, context
            )

            # Generate predictions
            predictions = self._generate_theory_predictions(hypotheses)

            # Determine scope
            scope = self._determine_scope(hypotheses, context)

            theory = Theory(
                name=name,
                description=description,
                hypotheses=hypotheses,
                coherence=coherence,
                explanatory_power=explanatory_power,
                predictions=predictions,
                scope=scope
            )

            logger.info(f"Synthesized theory: {name}")

        except Exception as e:
            logger.error(f"Error synthesizing theory: {e}")
            theory = Theory(
                name="Preliminary Theory",
                description=f"Theory regarding {query}",
                hypotheses=hypotheses,
                coherence=0.3,
                explanatory_power=0.3,
                scope="preliminary"
            )

        return theory

    def _generate_theory_name(self, query: str) -> str:
        """Generate a name for the theory"""
        # Extract key terms
        words = query.lower().split()[:5]
        # Create name from key terms
        name_parts = [w.capitalize() for w in words if len(w) > 3]
        if name_parts:
            return " ".join(name_parts[:3]) + " Theory"
        return "Integrated Theory"

    def _generate_theory_description(
        self,
        query: str,
        hypotheses: List[Hypothesis],
        context: Dict[str, Any]
    ) -> str:
        """Generate a description for the theory"""
        description = f"This theory integrates {len(hypotheses)} hypotheses to explain {query}."

        if hypotheses:
            description += f" Key components include: "
            description += "; ".join([h.statement[:80] + "..." for h in hypotheses[:3]])

        return description

    def _calculate_coherence(self, hypotheses: List[Hypothesis]) -> float:
        """Calculate how coherent the hypotheses are"""
        if len(hypotheses) < 2:
            return 0.5

        # Check for consistency
        coherence = 0.5

        # Increase coherence if hypotheses share domains
        domain_sets = [set(h.source_domains) for h in hypotheses]
        intersections = [len(set.intersection(*domain_sets[:i+1]))
                        for i in range(2, len(domain_sets)+1)]
        if intersections:
            coherence += 0.1 * max(intersections) / 10.0

        return min(coherence, 1.0)

    def _calculate_explanatory_power(
        self,
        hypotheses: List[Hypothesis],
        context: Dict[str, Any]
    ) -> float:
        """Calculate explanatory power of the theory"""
        # More hypotheses = more explanatory power (but may reduce coherence)
        power = 0.5 + 0.1 * len(hypotheses)
        return min(power, 1.0)

    def _generate_theory_predictions(
        self,
        hypotheses: List[Hypothesis]
    ) -> List[str]:
        """Generate predictions from the theory"""
        predictions = []

        # Collect predictions from all hypotheses
        for h in hypotheses:
            predictions.extend(h.predictions[:2])

        # Add theory-level predictions
        predictions.append("The theory should make accurate predictions across multiple domains")
        predictions.append("Interventions based on the theory should produce consistent outcomes")

        return list(set(predictions))

    def _determine_scope(
        self,
        hypotheses: List[Hypothesis],
        context: Dict[str, Any]
    ) -> str:
        """Determine the scope of the theory"""
        if len(hypotheses) >= 5:
            return "comprehensive"
        elif len(hypotheses) >= 3:
            return "intermediate"
        else:
            return "specific"


class MechanismExplainer:
    """
    Proposes mechanistic explanations for biological phenomena

    Generates step-by-step mechanistic explanations of how
    biological processes work.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize Mechanism Explainer

        Args:
            config: Configuration dictionary
        """
        self.config = config or {}

        # Common mechanistic patterns
        self.mechanistic_patterns = {
            'signaling': [
                "Ligand binds to receptor",
                "Receptor undergoes conformational change",
                "Downstream signaling cascade activated",
                "Cellular response elicited"
            ],
            'transcriptional': [
                "Transcription factor binds to DNA",
                "Chromatin remodeling occurs",
                "RNA polymerase recruited",
                "Gene transcription initiated",
                "mRNA processed and exported"
            ],
            'metabolic': [
                "Substrate enters pathway",
                "Enzyme catalyzes conversion",
                "Product generated",
                "Regulation via feedback",
                "Energy considerations"
            ],
            'protein_folding': [
                "Polypeptide synthesized",
                "Chaperone interaction",
                "Folding intermediates formed",
                "Native structure achieved",
                "Quality control verification"
            ]
        }

    def explain(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None
    ) -> Mechanism:
        """
        Generate a mechanistic explanation

        Args:
            query: Scientific query or phenomenon
            context: Additional context

        Returns:
            Mechanistic explanation
        """
        context = context or {}

        try:
            # Determine mechanism type
            mechanism_type = self._determine_mechanism_type(query)

            # Get mechanistic steps
            steps = self.mechanistic_patterns.get(
                mechanism_type,
                self.mechanistic_patterns['signaling']  # Default
            )

            # Extract entities
            entities = self._extract_entities(query, context)

            # Generate interactions
            interactions = self._generate_interactions(query, steps)

            # Determine dynamics
            dynamics = self._determine_dynamics(query, steps)

            mechanism = Mechanism(
                phenomenon=query,
                steps=steps,
                entities=entities,
                interactions=interactions,
                dynamics=dynamics,
                confidence=0.7
            )

            logger.info(f"Generated mechanistic explanation for: {query[:50]}...")

        except Exception as e:
            logger.error(f"Error generating mechanism: {e}")
            mechanism = Mechanism(
                phenomenon=query,
                steps=["Mechanism not yet characterized"],
                confidence=0.3
            )

        return mechanism

    def _determine_mechanism_type(self, query: str) -> str:
        """Determine the type of mechanism"""
        query_lower = query.lower()

        if any(term in query_lower for term in ['signal', 'pathway', 'cascade']):
            return 'signaling'
        elif any(term in query_lower for term in ['gene', 'transcription', 'expression']):
            return 'transcriptional'
        elif any(term in query_lower for term in ['metabolism', 'enzyme', 'pathway']):
            return 'metabolic'
        elif any(term in query_lower for term in ['folding', 'protein', 'chaperone']):
            return 'protein_folding'
        else:
            return 'signaling'  # Default

    def _extract_entities(
        self,
        query: str,
        context: Dict[str, Any]
    ) -> List[str]:
        """Extract biological entities from query"""
        entities = []

        # Common biological entity patterns
        entity_patterns = [
            r'\b[a-zA-Z]{2,} receptor\b',
            r'\b[a-zA-Z]{2,} protein\b',
            r'\b[a-zA-Z]{2,} factor\b',
            r'\b[a-zA-Z]{2,} enzyme\b'
        ]

        import re
        for pattern in entity_patterns:
            matches = re.findall(pattern, query, re.IGNORECASE)
            entities.extend(matches)

        return list(set(entities))

    def _generate_interactions(
        self,
        query: str,
        steps: List[str]
    ) -> List[str]:
        """Generate interactions between mechanistic steps"""
        interactions = []

        # Add temporal interactions
        for i in range(len(steps) - 1):
            interactions.append(f"{steps[i]} → {steps[i+1]}")

        # Add regulatory interactions
        interactions.append("Feedback regulation possible")
        interactions.append("Cross-talk with related pathways")

        return interactions

    def _determine_dynamics(
        self,
        query: str,
        steps: List[str]
    ) -> str:
        """Determine the temporal dynamics of the mechanism"""
        query_lower = query.lower()

        if any(term in query_lower for term in ['fast', 'rapid', 'quick']):
            return "Rapid dynamics (seconds to minutes)"
        elif any(term in query_lower for term in ['slow', 'gradual', 'progressive']):
            return "Slow dynamics (hours to days)"
        else:
            return "Intermediate dynamics (minutes to hours)"


class AbductiveTheoryFormer:
    """
    Main orchestrator for Abductive Theory Formation

    Coordinates hypothesis generation, knowledge gap identification,
    theory synthesis, and mechanism explanation.
    """

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize Abductive Theory Former

        Args:
            config: Configuration dictionary
        """
        self.config = config or {}

        # Initialize components
        self.hypothesis_generator = HypothesisGenerator(config)
        self.gap_identifier = KnowledgeGapIdentifier(config)
        self.theory_synthesizer = TheorySynthesizer(config)
        self.mechanism_explainer = MechanismExplainer(config)

        logger.info("Abductive Theory Former initialized")

    def generate_hypotheses(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None,
        num_hypotheses: int = 5
    ) -> List[Dict[str, Any]]:
        """
        Generate novel scientific hypotheses

        Args:
            query: Scientific query or phenomenon
            context: Additional context
            num_hypotheses: Number of hypotheses to generate

        Returns:
            List of hypotheses (as dictionaries)
        """
        hypotheses = self.hypothesis_generator.generate(
            query, context, num_hypotheses
        )
        return [h.to_dict() for h in hypotheses]

    def identify_gaps(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None,
        num_gaps: int = 5
    ) -> List[Dict[str, Any]]:
        """
        Identify knowledge gaps

        Args:
            query: Scientific query or phenomenon
            context: Additional context
            num_gaps: Number of gaps to identify

        Returns:
            List of knowledge gaps (as dictionaries)
        """
        gaps = self.gap_identifier.identify(query, context, num_gaps)
        return [g.to_dict() for g in gaps]

    def synthesize_theory(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None,
        hypotheses: Optional[List[Dict[str, Any]]] = None
    ) -> Dict[str, Any]:
        """
        Synthesize a theory from hypotheses

        Args:
            query: Scientific query or phenomenon
            context: Additional context
            hypotheses: List of hypotheses (as dictionaries)

        Returns:
            Synthesized theory (as dictionary)
        """
        # Convert dictionaries back to Hypothesis objects
        hypothesis_objects = []
        if hypotheses:
            for h_dict in hypotheses:
                hyp = Hypothesis(
                    statement=h_dict['statement'],
                    hypothesis_type=HypothesisType(h_dict['type']),
                    confidence=ConfidenceLevel(h_dict['confidence']),
                    evidence=h_dict.get('evidence', []),
                    predictions=h_dict.get('predictions', []),
                    falsifiable=h_dict.get('falsifiable', True),
                    novelty=h_dict.get('novelty', 0.5),
                    plausibility=h_dict.get('plausibility', 0.5),
                    source_domains=h_dict.get('source_domains', [])
                )
                hypothesis_objects.append(hyp)

        theory = self.theory_synthesizer.synthesize(
            query, context, hypothesis_objects
        )
        return theory.to_dict()

    def explain_mechanism(
        self,
        query: str,
        context: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Generate a mechanistic explanation

        Args:
            query: Scientific query or phenomenon
            context: Additional context

        Returns:
            Mechanistic explanation (as dictionary)
        """
        mechanism = self.mechanism_explainer.explain(query, context)
        return mechanism.to_dict()


__all__ = [
    # Main orchestrator
    'AbductiveTheoryFormer',

    # Components
    'HypothesisGenerator',
    'KnowledgeGapIdentifier',
    'TheorySynthesizer',
    'MechanismExplainer',

    # Data classes
    'Hypothesis',
    'KnowledgeGap',
    'Theory',
    'Mechanism',

    # Enums
    'HypothesisType',
    'ConfidenceLevel',
]
