"""Corpus part 3: tropical/travel-acquired, ENT/oral, and sexual health
conditions (expertise program Stage 2). Merged into CONDITIONS at import
time by knowledge.py — same pattern as knowledge_breadth.py.

Authored as tuples and expanded by a builder so each entry is declared
exactly once.
"""
from typing import Dict, List

from gpdisc_core.clinical_reasoning.schema import (
    ConditionProfile,
    InvestigationProfile,
    SymptomFrequency,
)

# (condition_id, name, category, prior, tier,
#  symptoms [(token, freq, spec)], discriminators, red_flags,
#  investigations [(name, purpose, sens, spec)],
#  management_first_line, safety_net, dangerous_mimic_of)
_ROWS = [
    # ---- Tropical / travel-acquired ----
    ("malaria_vivax", "Malaria (P. vivax / P. ovale)", "tropical", 0.002, "urgent",
     [("fever_after_travel", 0.95, 0.9), ("shivering_rigors", 0.8, 0.5),
      ("headache", 0.6, 0.2), ("fatigue", 0.5, 0.1), ("nausea", 0.4, 0.1)],
     ["Relapses weeks apart (hypnozoite liver stages) — ask about fever pattern over months",
      "Blood film speciation is mandatory: falciparum must be excluded first"],
     [],
     [("malaria_blood_film", "Thick and thin films x3 over 24-48h; species + parasitaemia", 0.95, 0.95),
      ("malaria_rdt", "Rapid antigen test — rapidly excludes falciparum", 0.90, 0.95)],
     "Same-day refer. Chloroquine (sensitive areas) then primaquine for radical cure AFTER G6PD check; falciparum excluded first.",
     "Drowsiness, jaundice or deterioration = emergency. One negative film never excludes malaria — 3 films over 24-48h.",
     ["influenza"]),
    ("chikungunya", "Chikungunya", "tropical", 0.0015, "routine",
     [("fever_after_travel", 0.9, 0.9), ("myalgia", 0.7, 0.2), ("joint_pain_severe", 0.7, 0.5),
      ("fever", 0.85, 0.1), ("headache", 0.5, 0.1)],
     ["Debilitating symmetric polyarthralgia outlasting the fever is the signature",
      "Exclude dengue before NSAIDs"],
     [],
     [("chikungunya_serology", "Paired serology (IgM/IgG)", 0.8, 0.95)],
     "Supportive: fluids, paracetamol; NSAIDs only after dengue excluded (platelet risk).",
     "Bleeding, bruising or abdominal pain → urgent review (dengue warning signs).",
     ["influenza"]),
    ("zika", "Zika virus infection", "tropical", 0.0008, "routine",
     [("fever_after_travel", 0.85, 0.85), ("fever", 0.7, 0.05), ("rash_generalised", 0.6, 0.3),
      ("headache", 0.5, 0.1), ("gritty_eye", 0.5, 0.4), ("joint_pain_severe", 0.4, 0.3)],
     ["Mild fever + rash + non-purulent conjunctivitis triad",
      "Reproductive intent is the key history — counselling drives management, not the virus"],
     [],
     [("zika_pcr", "PCR blood + urine within 14 days of symptom onset", 0.85, 0.95)],
     "Supportive. Pregnant: urgent obstetric referral. Contraception/abstinence: 8 weeks (all) / 6 months (male partner of pregnant woman).",
     "If pregnant or planning pregnancy → book review this week; do not conceive within the advised window.",
     []),
    ("yellow_fever", "Yellow fever (vaccine-preventable haemorrhagic fever)", "tropical", 0.0003, "urgent",
     [("fever_after_travel", 0.9, 0.9), ("fever", 0.85, 0.1), ("jaundice", 0.5, 0.6),
      ("headache", 0.6, 0.1), ("myalgia", 0.6, 0.1), ("vomiting", 0.5, 0.1),
      ("dark_urine", 0.3, 0.4), ("gum_bleeding", 0.2, 0.5)],
     ["Biphasic: remission then hepatorenal deterioration",
      "Ask vaccination and itinerary (yellow fever zone) — certificate errors are common"],
     ["Bleeding, confusion, oliguria → same-day admission"],
     [("yellow_fever_serology", "Serology/PCR via reference lab", 0.85, 0.95)],
     "Urgent ID referral; supportive care only — no antiviral; notifiable disease.",
     "Any bleeding or drowsiness → 999. Yellow fever has ~50% mortality in severe cases.",
     []),
    ("leptospirosis", "Leptospirosis (Weil disease)", "tropical", 0.0006, "urgent",
     [("fever_after_travel", 0.8, 0.8), ("post_exposure_freshwater", 0.6, 0.8), ("fever", 0.85, 0.1),
      ("myalgia", 0.75, 0.3), ("jaundice", 0.4, 0.5), ("headache", 0.6, 0.1),
      ("gritty_eye", 0.4, 0.5), ("dark_urine", 0.3, 0.4)],
     ["Freshwater/wet-sport exposure (lakes, rivers, floods, rats) + conjunctival suffusion",
      "Weil disease = jaundice + renal failure + bleeding — admit"],
     ["Oliguria, jaundice or haemoptysis → admission"],
     [("leptospira_serology", "Paired serology (MAT via reference lab)", 0.7, 0.95),
      ("fbc_uel", "FBC, U&E, LFT, CRP — renal + hepatic involvement", None, None)],
     "Doxycycline (mild) or benzylpenicillin IV; admit if jaundice/renal impairment.",
     "Falling urine output, new jaundice or bleeding → same-day admission.",
     ["influenza"]),
    ("schistosomiasis_acute", "Acute schistosomiasis (Katayama fever)", "tropical", 0.0008, "routine",
     [("fever_after_travel", 0.8, 0.7), ("post_exposure_freshwater", 0.85, 0.9),
      ("eosinophilia", 0.7, 0.8),
      ("fever", 0.7, 0.05), ("fatigue", 0.6, 0.1), ("itchy_skin", 0.5, 0.2), ("cough", 0.3, 0.1)],
     ["Prolonged freshwater exposure in Africa (Lake Malawi/Victoria, rafting) weeks before fever",
      "Itchy rash AT the water within a day (cercarial dermatitis) is a strong clue",
      "Serology negative before 6-12 weeks — timing of exposure decides the test interval"],
     [],
     [("schistosoma_serology", "Serology from 6-12 weeks after last exposure", 0.9, 0.95)],
     "Praziquantel after seroconversion (usually 6-12 wks post-exposure); corticosteroids for Katayama fever.",
     "Later haematuria or bloody diarrhoea → review (chronic schistosomiasis needs treatment regardless).",
     []),
    ("strongyloidiasis", "Strongyloidiasis (chronic threadworm)", "tropical", 0.0007, "routine",
     [("eosinophilia", 0.75, 0.85), ("itchy_skin", 0.5, 0.2), ("diarrhoea", 0.3, 0.1),
      ("abdominal_pain", 0.3, 0.1)],
     ["Larva currens — rapidly migrating weal on trunk/buttocks; infection persists DECADES",
      "Eosinophilia in anyone from a tropical area who will ever need steroids"],
     ["Immunosuppression (steroids, biologics, HTLV-1) can trigger fatal hyperinfection — treat first"],
     [("strongyloides_serology", "Serology — screening test of choice", 0.9, 0.95)],
     "Ivermectin 2 days (first line) or albendazole. MUST eradicate BEFORE any immunosuppression.",
     "Never start corticosteroids or biologics before excluding this in migrants/travellers with eosinophilia — hyperinfection is fatal.",
     []),
    ("hepatitis_a", "Hepatitis A", "tropical", 0.001, "routine",
     [("jaundice", 0.7, 0.7), ("fatigue", 0.8, 0.1), ("anorexia", 0.7, 0.2), ("nausea", 0.6, 0.1),
      ("dark_urine", 0.6, 0.4), ("fever_after_travel", 0.5, 0.3), ("itchy_skin", 0.3, 0.2)],
     ["Prodrome of anorexia/nausea BEFORE jaundice; ALT often >1000",
      "Contagious 2 weeks before to 1 week after jaundice — hygiene + contact vaccination"],
     ["Encephalopathy, bruising, hypoglycaemia → emergency (fulminant hepatitis)"],
     [("hepatitis_a_igm", "HAV IgM", 0.95, 0.95), ("lft", "ALT/AST markedly raised", None, None)],
     "Supportive; strict hand hygiene; notify UKHSA; vaccinate close contacts; exclude from food handling.",
     "Drowsiness, confusion or easy bruising → emergency same day.",
     []),
    ("hepatitis_e", "Hepatitis E", "tropical", 0.0005, "routine",
     [("jaundice", 0.7, 0.7), ("fatigue", 0.8, 0.1), ("nausea", 0.6, 0.1), ("dark_urine", 0.6, 0.4),
      ("fever_after_travel", 0.5, 0.3), ("vomiting", 0.4, 0.1)],
     ["Same picture as hepatitis A but the pregnancy question is decisive",
      "Underdiagnosed cause of acute hepatitis in older men"],
     ["Pregnancy — up to 25% mortality in third trimester: urgent obstetric + ID referral"],
     [("hepatitis_e_igm", "HEV IgM + PCR", 0.9, 0.95)],
     "Supportive; pregnant women need urgent joint obstetric/ID review.",
     "Pregnant or drowsy/confused → same-day hospital review.",
     []),
    ("amoebic_liver_abscess", "Amoebic liver abscess", "tropical", 0.0004, "urgent",
     [("fever_after_travel", 0.6, 0.4), ("ruq_pain", 0.85, 0.6), ("fever", 0.8, 0.1),
      ("sweating", 0.5, 0.1), ("weight_loss", 0.4, 0.2), ("abdominal_pain", 0.7, 0.2)],
     ["Single large right-lobe abscess; often no dysentery history",
      "Pleural effusion or basal lung changes beside RUQ pain"],
     ["Sudden severe pain or shoulder-tip pain → 999 (rupture)"],
     [("liver_us", "Ultrasound liver — single large abscess", 0.9, 0.9),
      ("amoebic_serology", "Entamoeba serology", 0.9, 0.95)],
     "Metronidazole 10 days + luminal agent (diloxanide/paromomycin); aspiration if large or impending rupture.",
     "Sudden severe abdominal or shoulder-tip pain → 999 (abscess rupture).",
     []),
    ("tick_typhus_african", "African tick-bite fever (rickettsia)", "tropical", 0.0008, "routine",
     [("fever_after_travel", 0.85, 0.8), ("eschar_tick_bite", 0.7, 0.9), ("fever", 0.8, 0.1),
      ("headache", 0.7, 0.1), ("myalgia", 0.6, 0.1), ("rash_generalised", 0.4, 0.3),
      ("swollen_glands", 0.5, 0.3)],
     ["Eschar (black crust at bite site) + regional nodes after game-park/bush travel",
      "Multiple eschars distinguish tick-bite fever from Mediterranean spotted fever"],
     ["Confusion or neck stiffness → emergency"],
     [("rickettsia_serology", "Paired serology; diagnosis usually retrospective", 0.7, 0.95)],
     "Doxycycline 7 days — clinical diagnosis, treat before serology confirms.",
     "Confusion, neck stiffness or non-fading rash → emergency.",
     []),
    ("giardia", "Giardiasis", "tropical", 0.003, "routine",
     [("diarrhoea", 0.8, 0.2), ("bloating", 0.7, 0.3), ("abdominal_pain", 0.6, 0.1),
      ("fatigue", 0.5, 0.1), ("weight_loss", 0.4, 0.2)],
     ["Foul-smelling fatty stools without blood; chronic weeks-long course",
      "Untreated water/hiking/stream exposure history"],
     [],
     [("stool_oap", "Stool microscopy x3 for ova, cysts and parasites", 0.85, 0.95)],
     "Metronidazole 400mg TDS 5 days (or tinidazole single dose); treat household contacts if symptomatic.",
     "Dehydration or blood in stool → review (reconsider bacterial causes).",
     []),
    ("vhf_suspect", "Viral haemorrhagic fever (suspect: Lassa/Ebola/Marburg)", "tropical", 0.0001, "emergency",
     [("fever_after_travel", 0.9, 0.5), ("fever", 0.9, 0.05), ("vomiting", 0.6, 0.1),
      ("diarrhoea", 0.6, 0.1), ("headache", 0.6, 0.05), ("gum_bleeding", 0.4, 0.4),
      ("bruising_easy", 0.3, 0.3), ("confusion", 0.3, 0.2)],
     ["Fever within 21 days of returning from endemic region (West/Central Africa)",
      "Risk triad: destination + symptoms + exposure (funeral, healthcare, bodily fluids)"],
     ["Isolation BEFORE investigation — no routine bloods leave the room"],
     [],
     "Isolate immediately, minimum contacts, PPE. Call the Imported Fever Service (UKHSA) BEFORE any test; ambulance transfer by prior arrangement only.",
     "999 with advance warning — never attend unannounced; VHF is a high-consequence infectious disease.",
     []),
    ("cholera_severe", "Cholera (severe)", "tropical", 0.0002, "urgent",
     [("rice_water_stool", 0.85, 0.95), ("diarrhoea", 0.9, 0.1), ("dehydration_signs", 0.8, 0.5),
      ("vomiting", 0.5, 0.1), ("reduced_urine_output", 0.5, 0.3)],
     ["Painless profuse rice-water stool — litres per hour",
      "Death is from dehydration, not the organism"],
     ["Rapid dehydration can kill within hours"],
     [("stool_culture", "Stool culture on special media", 0.9, 0.95)],
     "Aggressive ORS; IV Ringer's lactate if severe; doxycycline shortens illness and excretion.",
     "Sunken eyes, absent urine output or collapse → emergency rehydration now.",
     []),
    # ---- ENT / oral medicine ----
    ("quinsy_peritonsillar", "Peritonsillar abscess (quinsy)", "ent_oral", 0.002, "urgent",
     [("sore_throat", 0.95, 0.1), ("trismus", 0.6, 0.8), ("hot_potato_voice", 0.6, 0.8),
      ("dysphagia", 0.7, 0.4), ("ear_pain", 0.4, 0.3), ("fever", 0.6, 0.05),
      ("swollen_glands", 0.5, 0.2)],
     ["Unilateral severe pain + uvula deviation to the healthy side",
      "Failure of antibiotics for tonsillitis is the usual history"],
     ["Stridor or inability to swallow fluids → emergency"],
     [],
     "Same-day ENT: needle aspiration/incision + penicillin + single dexamethasone dose.",
     "Difficulty breathing or cannot swallow own saliva → emergency department now.",
     ["tonsillitis_strep"]),
    ("epiglottitis_adult", "Epiglottitis (adult)", "ent_oral", 0.0003, "emergency",
     [("sore_throat", 0.8, 0.05), ("stridor", 0.7, 0.9), ("drooling", 0.6, 0.9),
      ("dysphagia", 0.8, 0.3), ("fever", 0.6, 0.05), ("hot_potato_voice", 0.5, 0.5),
      ("hoarseness", 0.4, 0.2)],
     ["Severe odynophagia out of proportion to oral findings; sat upright, distressed",
      "Do NOT examine the throat or lie the patient down"],
     ["Complete airway obstruction can occur within minutes"],
     [],
     "999 immediately. Sit upright, oxygen, no throat examination. Senior ENT + anaesthetics; intubation in theatre.",
     "Airway obstruction risk — call 999 now; keep the patient sitting up.",
     ["tonsillitis_strep"]),
    ("malignant_otitis_externa", "Malignant (necrotising) otitis externa", "ent_oral", 0.0002, "urgent",
     [("ear_pain", 0.95, 0.1), ("ear_discharge", 0.7, 0.3), ("reduced_hearing", 0.4, 0.1),
      ("facial_droop", 0.2, 0.5)],
     ["Elderly diabetic; deep unrelenting otalgia failing 2 weeks of treatment",
      "Granulation tissue at the bony-cartilaginous junction is the signature finding"],
     ["Cranial nerve palsy (VII, IX-XII) = skull base spread"],
     [("ct_temporal_bone", "CT/MRI skull base", 0.8, 0.9),
      ("esr_crp", "ESR/CRP markedly raised", None, None)],
     "Urgent ENT: culture-directed IV anti-pseudomonal antibiotics 6+ weeks; biopsy granulations (exclude malignancy).",
     "Facial weakness, double vision or worsening pain → same-day ENT (skull base osteomyelitis).",
     []),
    ("oral_cancer_suspect", "Oral cancer (suspect)", "ent_oral", 0.0004, "two_week_wait",
     [("oral_ulcer_nonhealing", 0.7, 0.9), ("hoarseness", 0.3, 0.3), ("dysphagia", 0.3, 0.3),
      ("ear_pain", 0.2, 0.2), ("weight_loss", 0.2, 0.2), ("swollen_glands", 0.3, 0.2)],
     ["ANY oral ulcer, lump, red/white patch unexplained after 3 weeks = 2ww referral",
      "Tobacco + alcohol + betel nut multiply risk; floor of mouth and tongue borders are hotspots"],
     ["Ulcer/patch persisting beyond 3 weeks"],
     [],
     "Urgent suspected cancer referral (2ww). Stop tobacco/alcohol. Document site, size, fixation.",
     "Airway compromise, inability to eat or neck mass growing rapidly → urgent same-day review.",
     []),
    ("dental_abscess", "Dental abscess", "ent_oral", 0.005, "routine",
     [("toothache", 0.9, 0.9), ("swelling_hands_face", 0.5, 0.4), ("fever", 0.3, 0.05),
      ("trismus", 0.3, 0.5)],
     ["Percussion tenderness of one tooth; gum swelling",
      "Antibiotics never replace drainage by a dentist"],
     ["Trismus, submandibular swelling, raised floor of mouth → Ludwig's angina (emergency)"],
     [],
     "Dentist same week for drainage/source control. Amoxicillin or metronidazole ONLY if spreading infection or systemic features.",
     "Swelling crossing the midline, trismus, fever or swallowing difficulty → emergency (spreading cellulitis/Ludwig's angina).",
     []),
    ("oral_candidiasis", "Oral candidiasis (thrush)", "ent_oral", 0.003, "routine",
     [("oral_lesion_white", 0.8, 0.85), ("altered_taste", 0.4, 0.2), ("dysphagia", 0.3, 0.1)],
     ["Painless white plaques that scrape off (vs leukoplakia which does not)",
      "Check inhaled steroid technique, denture hygiene, diabetes, recent antibiotics"],
     ["Plaques not responding to 14 days of treatment — biopsy to exclude malignancy/dysplasia"],
     [],
     "Nystatin suspension or miconazole oral gel 7-14 days; rinse the mouth after steroid inhalers; check HbA1c.",
     "Persistent beyond 14 days, or painful ulceration underneath → review (2ww if suspicious).",
     []),
    ("glandular_fever", "Infectious mononucleosis (glandular fever)", "ent_oral", 0.004, "routine",
     [("sore_throat", 0.85, 0.05), ("swollen_glands", 0.8, 0.4), ("fatigue", 0.85, 0.1),
      ("fever", 0.7, 0.05),
      ("anorexia", 0.4, 0.1), ("night_sweats", 0.3, 0.1)],
     ["Posterior cervical chains; fatigue outlasting the sore throat by months",
      "Amoxicillin rash is a classic diagnostic clue, not an allergy"],
     ["Left upper quadrant pain (splenomegaly) — avoid contact sport 4 weeks"],
     [("monospot", "Heterophile antibody; false-negative in first 5 days and young children", 0.85, 0.95),
      ("ebv_serology", "EBV viral capsid IgM/IgG", 0.95, 0.95)],
     "Supportive: fluids, analgesia. AVOID contact sports 4 weeks (splenic rupture). Avoid ampicillin/amoxicillin.",
     "LUQ pain after trauma, or breathlessness → emergency.",
     ["tonsillitis_strep"]),
    ("aphthous_ulcers", "Aphthous mouth ulcers (benign)", "ent_oral", 0.006, "self_care",
     [("mouth_ulcers", 0.9, 0.5), ("sore_throat", 0.2, 0.02)],
     ["Recurrent round/ovoid shallow ulcers healing within 2 weeks",
      "Check iron/B12/folate and coeliac serology if recurrent or severe"],
     [],
     [],
     "Benzydamine mouthwash, chlorhexidine gel; avoid trigger foods. Iron/B12/folate + coeliac screen if recurrent.",
     "Any single ulcer not healed by 3 weeks must be referred under 2ww (oral cancer).",
     []),
    # ---- Sexual health ----
    ("chlamydia", "Chlamydia trachomatis infection", "sexual_health", 0.004, "routine",
     [("genital_discharge_male", 0.5, 0.7), ("dysuria", 0.4, 0.3), ("unprotected_sex", 0.6, 0.6),
      ("vaginal_discharge", 0.4, 0.2), ("testicular_pain", 0.2, 0.3),
      ("lower_abdominal_pain", 0.2, 0.1)],
     ["Majority asymptomatic — screening history beats symptom pattern",
      "Under-25s: annual screen regardless of symptoms"],
     [],
     [("naat_gc_ct", "First-void urine or self-taken vaginal NAAT", 0.95, 0.99)],
     "Doxycycline 100mg BD 7 days (azithromycin 1g if pregnant). Treat partners + partner notification; re-test at 3 months.",
     "Testicular swelling/pain or pelvic pain with fever → urgent (epididymitis/PID, infertility risk).",
     []),
    ("gonorrhoea", "Gonorrhoea", "sexual_health", 0.002, "urgent",
     [("genital_discharge_male", 0.7, 0.8), ("dysuria", 0.5, 0.3), ("unprotected_sex", 0.6, 0.6),
      ("vaginal_discharge", 0.4, 0.2), ("testicular_pain", 0.2, 0.3)],
     ["Purulent discharge, shorter incubation than chlamydia",
      "Resistance is the reason for culture + same-week treatment"],
     [],
     [("naat_gc_ct", "NAAT all sites; culture for susceptibility", 0.95, 0.99)],
     "Ceftriaxone 1g IM single dose; doxycycline if chlamydia not excluded. GUM referral for culture + partner notification.",
     "Pelvic pain with fever → same-day review (PID). Disseminated infection (joint pain, rash, fever) → urgent.",
     []),
    ("syphilis_primary", "Primary syphilis (chancre)", "sexual_health", 0.0005, "urgent",
     [("genital_ulcer", 0.85, 0.8), ("unprotected_sex", 0.7, 0.6), ("swollen_glands", 0.5, 0.4)],
     ["Classically PAINLESS indurated ulcer 10-90 days post-exposure — pain argues for herpes",
      "Regional painless inguinal nodes; spontaneous healing does NOT mean resolution"],
     [],
     [("syphilis_serology", "Treponemal EIA first-line; RPR/VDRL titre for activity", 0.95, 0.95)],
     "Benzathine penicillin G single IM dose (doxycycline if penicillin-allergic). GUM same-day; full STI screen; partner notification.",
     "Rash, fever or warts weeks later = secondary syphilis — return; untreated syphilis causes cardiovascular/neurological disease.",
     ["genital_herpes"]),
    ("genital_herpes", "Genital herpes (first episode)", "sexual_health", 0.003, "routine",
     [("genital_ulcer", 0.8, 0.6), ("dysuria", 0.5, 0.3), ("fever", 0.3, 0.05),
      ("swollen_glands", 0.5, 0.3)],
     ["PAINFUL clustered ulcers + dysuria distinguishes from syphilitic chancre",
      "First episodes are systemic (fever, myalgia); recurrences are milder and shorter"],
     ["Urinary retention or meningism → urgent review"],
     [("hsv_pcr", "PCR swab from lesion base", 0.95, 0.98)],
     "Aciclovir 400mg TDS 5 days if within 5 days of onset; saline bathing; simple analgesia; counsel on recurrence and asymptomatic shedding.",
     "Unable to pass urine, severe headache or light sensitivity → urgent review.",
     []),
    ("bacterial_vaginosis", "Bacterial vaginosis", "sexual_health", 0.006, "routine",
     [("fishy_vaginal_odour", 0.8, 0.85), ("vaginal_discharge", 0.8, 0.1)],
     ["Thin grey discharge, pH >4.5, NOT typically itchy or sore",
      "Itch points to thrush; soreness/ulceration to herpes or trichomonas"],
     ["Associated with late miscarriage and preterm birth in pregnancy"],
     [],
     "Metronidazole 400mg BD 5-7 days (or gel). Treat only if symptomatic; no partner treatment needed.",
     "If pregnant with previous preterm birth → inform midwife; pelvic pain or fever → review (PID).",
     []),
    ("trichomonas", "Trichomoniasis", "sexual_health", 0.001, "routine",
     [("vaginal_discharge", 0.8, 0.1), ("fishy_vaginal_odour", 0.5, 0.4), ("dysuria", 0.3, 0.2),
      ("itchy_skin", 0.4, 0.2)],
     ["Frothy yellow-green discharge with vulval soreness; strawberry cervix",
      "Both partners need treatment or ping-pongs indefinitely"],
     [],
     [("tv_naat", "NAAT (more sensitive than wet prep)", 0.95, 0.97)],
     "Metronidazole 400-500mg BD 7 days (or 2g single dose). Treat all partners; abstinence until treated.",
     "Pelvic pain or fever → review (PID).",
     []),
    ("epididymitis_sti", "Epididymitis (STI-associated, <35y)", "sexual_health", 0.001, "urgent",
     [("testicular_pain", 0.9, 0.5), ("testicular_swelling", 0.7, 0.5),
      ("genital_discharge_male", 0.3, 0.5),
      ("fever", 0.3, 0.1), ("dysuria", 0.3, 0.2), ("unprotected_sex", 0.5, 0.5)],
     ["Gradual onset over days vs torsion's sudden hours — but torsion is excluded FIRST",
      "Tenderness posterior to testis + cremasteric reflex present"],
     ["Sudden severe pain or vomiting → emergency: torsion until excluded"],
     [("naat_gc_ct", "NAAT urine; first-void", 0.95, 0.99)],
     "Doxycycline 100mg BD 14 days (add ceftriaxone if gonorrhoea plausible). Scrotal support, NSAIDs, rest; abstinence until treated.",
     "Sudden severe testicular pain, especially with vomiting → emergency same visit — torsion until excluded.",
     ["testicular_torsion"]),
]


def _build(rows) -> List[ConditionProfile]:
    out = []
    for (cid, name, cat, prior, tier, syms, disc, rf, invs, mgmt, sn, mimic) in rows:
        out.append(ConditionProfile(
            condition_id=cid, name=name, category=cat, prevalence_per_consult=prior,
            symptoms=[SymptomFrequency(s, f, sp) for (s, f, sp) in syms],
            discriminators=disc, red_flags=rf,
            investigations=[InvestigationProfile(n, p, s2, s3) for (n, p, s2, s3) in invs],
            management_first_line=mgmt, referral_tier=tier, safety_net=sn,
            dangerous_mimic_of=list(mimic)))
    return out


CONDITIONS_PART3 = _build(_ROWS)

SYMPTOM_SYNONYMS_PART3: Dict[str, List[str]] = {
    "rash_generalised": ["rash", "spots all over", "widespread rash", "rash on my trunk",
                         "skin rash", "came out in a rash"],
    "thrombocytopenia": ["thrombocytopenia", "low platelets", "platelets low",
                         "platelets are low", "low platelet count", "platelets of 80",
                         "platelets dropped"],
    "eosinophilia": ["eosinophilia", "raised eosinophils", "high eosinophils",
                     "eosinophils raised", "eosinophils high", "eosinophil count raised",
                     "high eosinophil count", "eosinophils of 1"],
    "post_exposure_freshwater": ["swam in a lake", "freshwater swimming",
                                 "swimming in the river",
                                 "lake swimming", "waded", "snorkelling in fresh water",
                                 "white water rafting", "swimming in lake", "in the lake"],
    "rice_water_stool": ["rice water", "profuse watery diarrhoea", "waterfall diarrhoea"],
    "toothache": ["toothache", "tooth pain", "dental pain", "painful tooth",
                  "tooth is killing me", "pain in my tooth"],
    "mouth_ulcers": ["mouth ulcers", "oral ulcers", "ulcers in my mouth", "aphthous ulcers",
                     "canker sores", "multiple mouth ulcers"],
    "oral_ulcer_nonhealing": ["mouth ulcer not healing", "oral ulcer for 3 weeks",
                              "non-healing mouth ulcer", "ulcer in my mouth for weeks",
                              "sore in my mouth for a month", "mouth ulcer that won't heal",
                              "mouth ulcer for over 3 weeks",
                              "mouth ulcer that has not healed", "has not healed",
                              "ulcer not healed"],
    "oral_lesion_white": ["white patches in my mouth", "white coating on my tongue",
                          "oral thrush", "white patches on my tongue",
                          "white patches in mouth",
                          "candida in the mouth"],
    "trismus": ["can't open my mouth", "cannot open my mouth", "difficulty opening my mouth",
                "trismus", "unable to open my mouth fully", "jaw won't open",
                "struggling to open my mouth"],
    "hot_potato_voice": ["hot potato voice", "muffled voice", "muffled speech",
                         "sounds like hot potato"],
    "drooling": ["drooling", "dribbling", "cannot swallow saliva", "unable to swallow saliva",
                 "can't swallow my saliva"],
    "eschar_tick_bite": ["tick bite", "eschar", "black scab", "pulled a tick off",
                         "tick embedded", "black crust at the bite"],
    "genital_ulcer": ["genital ulcer", "ulcer on my penis", "sore on my penis",
                      "ulcer on genitals", "painless genital sore", "chancre",
                      "ulcer on the penis", "vaginal ulcer", "ulcer on the vulva",
                      "sore on my genitals"],
    "genital_discharge_male": ["discharge from penis", "urethral discharge",
                               "penile discharge", "discharge from my penis",
                               "pus from penis"],
    "fishy_vaginal_odour": ["fishy smell", "fishy discharge", "fishy odour",
                            "smells fishy"],
    "unprotected_sex": ["unprotected sex", "without a condom", "new sexual partner",
                        "one night stand", "sex without a condom", "condom broke",
                        "didn't use a condom"],
}
